/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/RAM-2500HD-CC-696j-Body.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/RAM-2500HD-CC-696j-Body.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group scale={0.025}>
          <group position={[-1.006, 0, -0.005]}>
            <group position={[80.011, 30.566, 0.048]} rotation={[-Math.PI, 0, 0]} scale={-1}>
              <mesh geometry={nodes.Geom3D__26.geometry} material={materials.Material1} position={[56.824, -24.854, -3.304]} rotation={[0, -1.571, 0]} />
              <mesh geometry={nodes.Geom3D__27.geometry} material={materials.Material1} position={[1.006, 0, -0.043]} />
            </group>
            <group position={[79.442, 77.816, 1.505]} rotation={[-Math.PI, 0, 0]} scale={-1}>
              <group position={[0.25, 0, 0]}>
                <group position={[0.187, 27.709, 24.186]} rotation={[0, -Math.PI / 2, 0]} scale={[0.503, 0.488, 0.488]}>
                  <group position={[0, 0.875, 0]} rotation={[-Math.PI, 0, Math.PI]} scale={-1}>
                    <mesh geometry={nodes.Geom3D_Piano_Hinge_Leaf.geometry} material={materials['[Color_000]']} />
                    <mesh geometry={nodes.Geom3D_6.geometry} material={materials['[Color_000]']} />
                  </group>
                  <mesh geometry={nodes.Geom3D__30.geometry} material={nodes.Geom3D__30.material} />
                  <mesh geometry={nodes['Geom3D_Piano_Hinge_Leaf#2'].geometry} material={nodes['Geom3D_Piano_Hinge_Leaf#2'].material} position={[-0.999, 0.875, 0.25]} rotation={[Math.PI, 0, 0]} />
                </group>
                <group position={[0.187, 27.709, 30.217]} rotation={[0, -Math.PI / 2, 0]} scale={[0.503, 0.488, 0.488]}>
                  <group position={[0, 0.875, 0]} rotation={[-Math.PI, 0, Math.PI]} scale={-1}>
                    <mesh geometry={nodes.Geom3D_Piano_Hinge_Leaf_1.geometry} material={materials['[Color_000]']} />
                    <mesh geometry={nodes.Geom3D_7.geometry} material={materials['[Color_000]']} />
                  </group>
                  <mesh geometry={nodes.Geom3D__31.geometry} material={nodes.Geom3D__31.material} />
                  <mesh geometry={nodes['Geom3D_Piano_Hinge_Leaf#2_1'].geometry} material={nodes['Geom3D_Piano_Hinge_Leaf#2_1'].material} position={[-0.999, 0.875, 0.25]} rotation={[Math.PI, 0, 0]} />
                </group>
                <group position={[0.187, 27.709, 0.062]} rotation={[0, -Math.PI / 2, 0]} scale={[0.503, 0.488, 0.488]}>
                  <group position={[0, 0.875, 0]} rotation={[-Math.PI, 0, Math.PI]} scale={-1}>
                    <mesh geometry={nodes.Geom3D_Piano_Hinge_Leaf_2.geometry} material={materials['[Color_000]']} />
                    <mesh geometry={nodes.Geom3D_8.geometry} material={materials['[Color_000]']} />
                  </group>
                  <mesh geometry={nodes.Geom3D__32.geometry} material={nodes.Geom3D__32.material} />
                  <mesh geometry={nodes['Geom3D_Piano_Hinge_Leaf#2_2'].geometry} material={nodes['Geom3D_Piano_Hinge_Leaf#2_2'].material} position={[-0.999, 0.875, 0.25]} rotation={[Math.PI, 0, 0]} />
                </group>
                <group position={[0.187, 27.709, 6.094]} rotation={[0, -Math.PI / 2, 0]} scale={[0.503, 0.488, 0.488]}>
                  <group position={[0, 0.875, 0]} rotation={[-Math.PI, 0, Math.PI]} scale={-1}>
                    <mesh geometry={nodes.Geom3D_Piano_Hinge_Leaf_3.geometry} material={materials['[Color_000]']} />
                    <mesh geometry={nodes.Geom3D_9.geometry} material={materials['[Color_000]']} />
                  </group>
                  <mesh geometry={nodes.Geom3D__33.geometry} material={nodes.Geom3D__33.material} />
                  <mesh geometry={nodes['Geom3D_Piano_Hinge_Leaf#2_3'].geometry} material={nodes['Geom3D_Piano_Hinge_Leaf#2_3'].material} position={[-0.999, 0.875, 0.25]} rotation={[Math.PI, 0, 0]} />
                </group>
                <group position={[0.187, 27.709, 12.124]} rotation={[0, -Math.PI / 2, 0]} scale={[0.503, 0.488, 0.488]}>
                  <group position={[0, 0.875, 0]} rotation={[-Math.PI, 0, Math.PI]} scale={-1}>
                    <mesh geometry={nodes.Geom3D_Piano_Hinge_Leaf_4.geometry} material={materials['[Color_000]']} />
                    <mesh geometry={nodes.Geom3D_10.geometry} material={materials['[Color_000]']} />
                  </group>
                  <mesh geometry={nodes.Geom3D__34.geometry} material={nodes.Geom3D__34.material} />
                  <mesh geometry={nodes['Geom3D_Piano_Hinge_Leaf#2_4'].geometry} material={nodes['Geom3D_Piano_Hinge_Leaf#2_4'].material} position={[-0.999, 0.875, 0.25]} rotation={[Math.PI, 0, 0]} />
                </group>
                <group position={[0.187, 27.709, 18.155]} rotation={[0, -Math.PI / 2, 0]} scale={[0.503, 0.488, 0.488]}>
                  <group position={[0, 0.875, 0]} rotation={[-Math.PI, 0, Math.PI]} scale={-1}>
                    <mesh geometry={nodes.Geom3D_Piano_Hinge_Leaf_5.geometry} material={materials['[Color_000]']} />
                    <mesh geometry={nodes.Geom3D_11.geometry} material={materials['[Color_000]']} />
                  </group>
                  <mesh geometry={nodes.Geom3D__35.geometry} material={nodes.Geom3D__35.material} />
                  <mesh geometry={nodes['Geom3D_Piano_Hinge_Leaf#2_5'].geometry} material={nodes['Geom3D_Piano_Hinge_Leaf#2_5'].material} position={[-0.999, 0.875, 0.25]} rotation={[Math.PI, 0, 0]} />
                </group>
                <mesh geometry={nodes.Geom3D__36.geometry} material={nodes.Geom3D__36.material} position={[-0.375, 0, 0]} />
              </group>
              <mesh geometry={nodes.Geom3D.geometry} material={materials.Material} position={[0.25, 1.431, 15.874]} />
            </group>
            <group position={[79.442, 10.066, 1.505]} rotation={[-Math.PI, 0, 0]} scale={-1}>
              <group position={[0.25, -10, 0]}>
                <group position={[0.187, 27.709, 24.186]} rotation={[0, -Math.PI / 2, 0]} scale={[0.503, 0.488, 0.488]}>
                  <group position={[0, 0.875, 0]} rotation={[-Math.PI, 0, Math.PI]} scale={-1}>
                    <mesh geometry={nodes.Geom3D_Piano_Hinge_Leaf_6.geometry} material={materials['[Color_000]']} />
                    <mesh geometry={nodes.Geom3D_12.geometry} material={materials['[Color_000]']} />
                  </group>
                  <mesh geometry={nodes.Geom3D__37.geometry} material={nodes.Geom3D__37.material} />
                  <mesh geometry={nodes['Geom3D_Piano_Hinge_Leaf#2_6'].geometry} material={nodes['Geom3D_Piano_Hinge_Leaf#2_6'].material} position={[-0.999, 0.875, 0.25]} rotation={[Math.PI, 0, 0]} />
                </group>
                <group position={[0.187, 27.709, 30.217]} rotation={[0, -Math.PI / 2, 0]} scale={[0.503, 0.488, 0.488]}>
                  <group position={[0, 0.875, 0]} rotation={[-Math.PI, 0, Math.PI]} scale={-1}>
                    <mesh geometry={nodes.Geom3D_Piano_Hinge_Leaf_7.geometry} material={materials['[Color_000]']} />
                    <mesh geometry={nodes.Geom3D_13.geometry} material={materials['[Color_000]']} />
                  </group>
                  <mesh geometry={nodes.Geom3D__38.geometry} material={nodes.Geom3D__38.material} />
                  <mesh geometry={nodes['Geom3D_Piano_Hinge_Leaf#2_7'].geometry} material={nodes['Geom3D_Piano_Hinge_Leaf#2_7'].material} position={[-0.999, 0.875, 0.25]} rotation={[Math.PI, 0, 0]} />
                </group>
                <group position={[0.187, 27.709, 0.062]} rotation={[0, -Math.PI / 2, 0]} scale={[0.503, 0.488, 0.488]}>
                  <group position={[0, 0.875, 0]} rotation={[-Math.PI, 0, Math.PI]} scale={-1}>
                    <mesh geometry={nodes.Geom3D_Piano_Hinge_Leaf_8.geometry} material={materials['[Color_000]']} />
                    <mesh geometry={nodes.Geom3D_14.geometry} material={materials['[Color_000]']} />
                  </group>
                  <mesh geometry={nodes.Geom3D__39.geometry} material={nodes.Geom3D__39.material} />
                  <mesh geometry={nodes['Geom3D_Piano_Hinge_Leaf#2_8'].geometry} material={nodes['Geom3D_Piano_Hinge_Leaf#2_8'].material} position={[-0.999, 0.875, 0.25]} rotation={[Math.PI, 0, 0]} />
                </group>
                <group position={[0.187, 27.709, 6.094]} rotation={[0, -Math.PI / 2, 0]} scale={[0.503, 0.488, 0.488]}>
                  <group position={[0, 0.875, 0]} rotation={[-Math.PI, 0, Math.PI]} scale={-1}>
                    <mesh geometry={nodes.Geom3D_Piano_Hinge_Leaf_9.geometry} material={materials['[Color_000]']} />
                    <mesh geometry={nodes.Geom3D_15.geometry} material={materials['[Color_000]']} />
                  </group>
                  <mesh geometry={nodes.Geom3D__40.geometry} material={nodes.Geom3D__40.material} />
                  <mesh geometry={nodes['Geom3D_Piano_Hinge_Leaf#2_9'].geometry} material={nodes['Geom3D_Piano_Hinge_Leaf#2_9'].material} position={[-0.999, 0.875, 0.25]} rotation={[Math.PI, 0, 0]} />
                </group>
                <group position={[0.187, 27.709, 12.124]} rotation={[0, -Math.PI / 2, 0]} scale={[0.503, 0.488, 0.488]}>
                  <group position={[0, 0.875, 0]} rotation={[-Math.PI, 0, Math.PI]} scale={-1}>
                    <mesh geometry={nodes.Geom3D_Piano_Hinge_Leaf_10.geometry} material={materials['[Color_000]']} />
                    <mesh geometry={nodes.Geom3D_16.geometry} material={materials['[Color_000]']} />
                  </group>
                  <mesh geometry={nodes.Geom3D__41.geometry} material={nodes.Geom3D__41.material} />
                  <mesh geometry={nodes['Geom3D_Piano_Hinge_Leaf#2_10'].geometry} material={nodes['Geom3D_Piano_Hinge_Leaf#2_10'].material} position={[-0.999, 0.875, 0.25]} rotation={[Math.PI, 0, 0]} />
                </group>
                <group position={[0.187, 27.709, 18.155]} rotation={[0, -Math.PI / 2, 0]} scale={[0.503, 0.488, 0.488]}>
                  <group position={[0, 0.875, 0]} rotation={[-Math.PI, 0, Math.PI]} scale={-1}>
                    <mesh geometry={nodes.Geom3D_Piano_Hinge_Leaf_11.geometry} material={materials['[Color_000]']} />
                    <mesh geometry={nodes.Geom3D_17.geometry} material={materials['[Color_000]']} />
                  </group>
                  <mesh geometry={nodes.Geom3D__42.geometry} material={nodes.Geom3D__42.material} />
                  <mesh geometry={nodes['Geom3D_Piano_Hinge_Leaf#2_11'].geometry} material={nodes['Geom3D_Piano_Hinge_Leaf#2_11'].material} position={[-0.999, 0.875, 0.25]} rotation={[Math.PI, 0, 0]} />
                </group>
                <mesh geometry={nodes.Geom3D__43.geometry} material={nodes.Geom3D__43.material} position={[-0.375, 0, 0]} />
              </group>
              <mesh geometry={nodes.Geom3D_1.geometry} material={materials.Material} position={[0.25, 1.431, 15.874]} />
            </group>
            <group position={[79.442, 29.816, 21.883]} rotation={[-Math.PI, 0, 0]} scale={-1}>
              <group position={[-0.063, 0, 0.122]}>
                <group position={[0.5, 0.068, 0.305]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.549, 0.488, 0.488]}>
                  <group position={[0, 0.875, 0]} rotation={[-Math.PI, 0, Math.PI]} scale={-1}>
                    <mesh geometry={nodes.Geom3D_Piano_Hinge_Leaf_12.geometry} material={materials['[Color_000]']} />
                    <mesh geometry={nodes.Geom3D_18.geometry} material={materials['[Color_000]']} />
                  </group>
                  <mesh geometry={nodes.Geom3D__45.geometry} material={nodes.Geom3D__45.material} />
                  <mesh geometry={nodes['Geom3D_Piano_Hinge_Leaf#2_12'].geometry} material={nodes['Geom3D_Piano_Hinge_Leaf#2_12'].material} position={[-0.999, 0.875, 0.25]} rotation={[Math.PI, 0, 0]} />
                </group>
                <group position={[0.5, 6.656, 0.305]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.549, 0.488, 0.488]}>
                  <group position={[0, 0.875, 0]} rotation={[-Math.PI, 0, Math.PI]} scale={-1}>
                    <mesh geometry={nodes.Geom3D_Piano_Hinge_Leaf_13.geometry} material={materials['[Color_000]']} />
                    <mesh geometry={nodes.Geom3D_19.geometry} material={materials['[Color_000]']} />
                  </group>
                  <mesh geometry={nodes.Geom3D__46.geometry} material={nodes.Geom3D__46.material} />
                  <mesh geometry={nodes['Geom3D_Piano_Hinge_Leaf#2_13'].geometry} material={nodes['Geom3D_Piano_Hinge_Leaf#2_13'].material} position={[-0.999, 0.875, 0.25]} rotation={[Math.PI, 0, 0]} />
                </group>
                <group position={[0.5, 13.243, 0.305]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.549, 0.488, 0.488]}>
                  <group position={[0, 0.875, 0]} rotation={[-Math.PI, 0, Math.PI]} scale={-1}>
                    <mesh geometry={nodes.Geom3D_Piano_Hinge_Leaf_14.geometry} material={materials['[Color_000]']} />
                    <mesh geometry={nodes.Geom3D_20.geometry} material={materials['[Color_000]']} />
                  </group>
                  <mesh geometry={nodes.Geom3D__47.geometry} material={nodes.Geom3D__47.material} />
                  <mesh geometry={nodes['Geom3D_Piano_Hinge_Leaf#2_14'].geometry} material={nodes['Geom3D_Piano_Hinge_Leaf#2_14'].material} position={[-0.999, 0.875, 0.25]} rotation={[Math.PI, 0, 0]} />
                </group>
                <group position={[0.5, 19.831, 0.305]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.549, 0.488, 0.488]}>
                  <group position={[0, 0.875, 0]} rotation={[-Math.PI, 0, Math.PI]} scale={-1}>
                    <mesh geometry={nodes.Geom3D_Piano_Hinge_Leaf_15.geometry} material={materials['[Color_000]']} />
                    <mesh geometry={nodes.Geom3D_21.geometry} material={materials['[Color_000]']} />
                  </group>
                  <mesh geometry={nodes.Geom3D__48.geometry} material={nodes.Geom3D__48.material} />
                  <mesh geometry={nodes['Geom3D_Piano_Hinge_Leaf#2_15'].geometry} material={nodes['Geom3D_Piano_Hinge_Leaf#2_15'].material} position={[-0.999, 0.875, 0.25]} rotation={[Math.PI, 0, 0]} />
                </group>
                <group position={[0.5, 26.419, 0.305]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.549, 0.488, 0.488]}>
                  <group position={[0, 0.875, 0]} rotation={[-Math.PI, 0, Math.PI]} scale={-1}>
                    <mesh geometry={nodes.Geom3D_Piano_Hinge_Leaf_16.geometry} material={materials['[Color_000]']} />
                    <mesh geometry={nodes.Geom3D_22.geometry} material={materials['[Color_000]']} />
                  </group>
                  <mesh geometry={nodes.Geom3D__49.geometry} material={nodes.Geom3D__49.material} />
                  <mesh geometry={nodes['Geom3D_Piano_Hinge_Leaf#2_16'].geometry} material={nodes['Geom3D_Piano_Hinge_Leaf#2_16'].material} position={[-0.999, 0.875, 0.25]} rotation={[Math.PI, 0, 0]} />
                </group>
                <group position={[0.5, 33.006, 0.305]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.549, 0.488, 0.488]}>
                  <group position={[0, 0.875, 0]} rotation={[-Math.PI, 0, Math.PI]} scale={-1}>
                    <mesh geometry={nodes.Geom3D_Piano_Hinge_Leaf_17.geometry} material={materials['[Color_000]']} />
                    <mesh geometry={nodes.Geom3D_23.geometry} material={materials['[Color_000]']} />
                  </group>
                  <mesh geometry={nodes.Geom3D__50.geometry} material={nodes.Geom3D__50.material} />
                  <mesh geometry={nodes['Geom3D_Piano_Hinge_Leaf#2_17'].geometry} material={nodes['Geom3D_Piano_Hinge_Leaf#2_17'].material} position={[-0.999, 0.875, 0.25]} rotation={[Math.PI, 0, 0]} />
                </group>
                <group position={[0.5, 39.593, 0.305]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.549, 0.488, 0.488]}>
                  <group position={[0, 0.875, 0]} rotation={[-Math.PI, 0, Math.PI]} scale={-1}>
                    <mesh geometry={nodes.Geom3D_Piano_Hinge_Leaf_18.geometry} material={materials['[Color_000]']} />
                    <mesh geometry={nodes.Geom3D_24.geometry} material={materials['[Color_000]']} />
                  </group>
                  <mesh geometry={nodes.Geom3D__51.geometry} material={nodes.Geom3D__51.material} />
                  <mesh geometry={nodes['Geom3D_Piano_Hinge_Leaf#2_18'].geometry} material={nodes['Geom3D_Piano_Hinge_Leaf#2_18'].material} position={[-0.999, 0.875, 0.25]} rotation={[Math.PI, 0, 0]} />
                </group>
                <mesh geometry={nodes.Geom3D__44.geometry} material={nodes.Geom3D__44.material} position={[0.375, 0, 0]} />
              </group>
              <mesh geometry={nodes.Geom3D_2.geometry} material={materials.Material} position={[0.25, 20.916, 14.442]} rotation={[-Math.PI / 2, 0, 0]} />
            </group>
            <group position={[0, 30.566, 0.048]}>
              <mesh geometry={nodes.Geom3D__28.geometry} material={materials.Material1} position={[56.824, -24.854, -3.304]} rotation={[0, -1.571, 0]} />
              <mesh geometry={nodes.Geom3D__29.geometry} material={materials.Material1} position={[1.006, 0, -0.043]} />
            </group>
            <group position={[0.569, 29.816, 21.883]}>
              <group position={[-0.063, 0, 0.122]}>
                <group position={[0.5, 0.068, 0.305]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.549, 0.488, 0.488]}>
                  <group position={[0, 0.875, 0]} rotation={[-Math.PI, 0, Math.PI]} scale={-1}>
                    <mesh geometry={nodes.Geom3D_Piano_Hinge_Leaf_19.geometry} material={materials['[Color_000]']} />
                    <mesh geometry={nodes.Geom3D_25.geometry} material={materials['[Color_000]']} />
                  </group>
                  <mesh geometry={nodes.Geom3D__53.geometry} material={materials.Material1} />
                  <mesh geometry={nodes['Geom3D_Piano_Hinge_Leaf#2_19'].geometry} material={materials.Material1} position={[-0.999, 0.875, 0.25]} rotation={[Math.PI, 0, 0]} />
                </group>
                <group position={[0.5, 6.656, 0.305]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.549, 0.488, 0.488]}>
                  <group position={[0, 0.875, 0]} rotation={[-Math.PI, 0, Math.PI]} scale={-1}>
                    <mesh geometry={nodes.Geom3D_Piano_Hinge_Leaf_20.geometry} material={materials['[Color_000]']} />
                    <mesh geometry={nodes.Geom3D_26.geometry} material={materials['[Color_000]']} />
                  </group>
                  <mesh geometry={nodes.Geom3D__54.geometry} material={materials.Material1} />
                  <mesh geometry={nodes['Geom3D_Piano_Hinge_Leaf#2_20'].geometry} material={materials.Material1} position={[-0.999, 0.875, 0.25]} rotation={[Math.PI, 0, 0]} />
                </group>
                <group position={[0.5, 13.243, 0.305]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.549, 0.488, 0.488]}>
                  <group position={[0, 0.875, 0]} rotation={[-Math.PI, 0, Math.PI]} scale={-1}>
                    <mesh geometry={nodes.Geom3D_Piano_Hinge_Leaf_21.geometry} material={materials['[Color_000]']} />
                    <mesh geometry={nodes.Geom3D_27.geometry} material={materials['[Color_000]']} />
                  </group>
                  <mesh geometry={nodes.Geom3D__55.geometry} material={materials.Material1} />
                  <mesh geometry={nodes['Geom3D_Piano_Hinge_Leaf#2_21'].geometry} material={materials.Material1} position={[-0.999, 0.875, 0.25]} rotation={[Math.PI, 0, 0]} />
                </group>
                <group position={[0.5, 19.831, 0.305]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.549, 0.488, 0.488]}>
                  <group position={[0, 0.875, 0]} rotation={[-Math.PI, 0, Math.PI]} scale={-1}>
                    <mesh geometry={nodes.Geom3D_Piano_Hinge_Leaf_22.geometry} material={materials['[Color_000]']} />
                    <mesh geometry={nodes.Geom3D_28.geometry} material={materials['[Color_000]']} />
                  </group>
                  <mesh geometry={nodes.Geom3D__56.geometry} material={materials.Material1} />
                  <mesh geometry={nodes['Geom3D_Piano_Hinge_Leaf#2_22'].geometry} material={materials.Material1} position={[-0.999, 0.875, 0.25]} rotation={[Math.PI, 0, 0]} />
                </group>
                <group position={[0.5, 26.419, 0.305]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.549, 0.488, 0.488]}>
                  <group position={[0, 0.875, 0]} rotation={[-Math.PI, 0, Math.PI]} scale={-1}>
                    <mesh geometry={nodes.Geom3D_Piano_Hinge_Leaf_23.geometry} material={materials['[Color_000]']} />
                    <mesh geometry={nodes.Geom3D_29.geometry} material={materials['[Color_000]']} />
                  </group>
                  <mesh geometry={nodes.Geom3D__57.geometry} material={materials.Material1} />
                  <mesh geometry={nodes['Geom3D_Piano_Hinge_Leaf#2_23'].geometry} material={materials.Material1} position={[-0.999, 0.875, 0.25]} rotation={[Math.PI, 0, 0]} />
                </group>
                <group position={[0.5, 33.006, 0.305]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.549, 0.488, 0.488]}>
                  <group position={[0, 0.875, 0]} rotation={[-Math.PI, 0, Math.PI]} scale={-1}>
                    <mesh geometry={nodes.Geom3D_Piano_Hinge_Leaf_24.geometry} material={materials['[Color_000]']} />
                    <mesh geometry={nodes.Geom3D_30.geometry} material={materials['[Color_000]']} />
                  </group>
                  <mesh geometry={nodes.Geom3D__58.geometry} material={materials.Material1} />
                  <mesh geometry={nodes['Geom3D_Piano_Hinge_Leaf#2_24'].geometry} material={materials.Material1} position={[-0.999, 0.875, 0.25]} rotation={[Math.PI, 0, 0]} />
                </group>
                <group position={[0.5, 39.593, 0.305]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.549, 0.488, 0.488]}>
                  <group position={[0, 0.875, 0]} rotation={[-Math.PI, 0, Math.PI]} scale={-1}>
                    <mesh geometry={nodes.Geom3D_Piano_Hinge_Leaf_25.geometry} material={materials['[Color_000]']} />
                    <mesh geometry={nodes.Geom3D_31.geometry} material={materials['[Color_000]']} />
                  </group>
                  <mesh geometry={nodes.Geom3D__59.geometry} material={materials.Material1} />
                  <mesh geometry={nodes['Geom3D_Piano_Hinge_Leaf#2_25'].geometry} material={materials.Material1} position={[-0.999, 0.875, 0.25]} rotation={[Math.PI, 0, 0]} />
                </group>
                <mesh geometry={nodes.Geom3D__52.geometry} material={materials.Material1} position={[0.375, 0, 0]} />
              </group>
              <mesh geometry={nodes.Geom3D_3.geometry} material={materials.Material} position={[0.25, 20.916, 14.442]} rotation={[-Math.PI / 2, 0, 0]} />
            </group>
            <group position={[0.569, 10.066, 1.505]}>
              <group position={[0.25, -10, 0]}>
                <group position={[0.187, 27.709, 24.186]} rotation={[0, -Math.PI / 2, 0]} scale={[0.503, 0.488, 0.488]}>
                  <group position={[0, 0.875, 0]} rotation={[-Math.PI, 0, Math.PI]} scale={-1}>
                    <mesh geometry={nodes.Geom3D_Piano_Hinge_Leaf_26.geometry} material={materials['[Color_000]']} />
                    <mesh geometry={nodes.Geom3D_32.geometry} material={materials['[Color_000]']} />
                  </group>
                  <mesh geometry={nodes.Geom3D__60.geometry} material={materials.Material1} />
                  <mesh geometry={nodes['Geom3D_Piano_Hinge_Leaf#2_26'].geometry} material={materials.Material1} position={[-0.999, 0.875, 0.25]} rotation={[Math.PI, 0, 0]} />
                </group>
                <group position={[0.187, 27.709, 30.217]} rotation={[0, -Math.PI / 2, 0]} scale={[0.503, 0.488, 0.488]}>
                  <group position={[0, 0.875, 0]} rotation={[-Math.PI, 0, Math.PI]} scale={-1}>
                    <mesh geometry={nodes.Geom3D_Piano_Hinge_Leaf_27.geometry} material={materials['[Color_000]']} />
                    <mesh geometry={nodes.Geom3D_33.geometry} material={materials['[Color_000]']} />
                  </group>
                  <mesh geometry={nodes.Geom3D__61.geometry} material={materials.Material1} />
                  <mesh geometry={nodes['Geom3D_Piano_Hinge_Leaf#2_27'].geometry} material={materials.Material1} position={[-0.999, 0.875, 0.25]} rotation={[Math.PI, 0, 0]} />
                </group>
                <group position={[0.187, 27.709, 0.062]} rotation={[0, -Math.PI / 2, 0]} scale={[0.503, 0.488, 0.488]}>
                  <group position={[0, 0.875, 0]} rotation={[-Math.PI, 0, Math.PI]} scale={-1}>
                    <mesh geometry={nodes.Geom3D_Piano_Hinge_Leaf_28.geometry} material={materials['[Color_000]']} />
                    <mesh geometry={nodes.Geom3D_34.geometry} material={materials['[Color_000]']} />
                  </group>
                  <mesh geometry={nodes.Geom3D__62.geometry} material={materials.Material1} />
                  <mesh geometry={nodes['Geom3D_Piano_Hinge_Leaf#2_28'].geometry} material={materials.Material1} position={[-0.999, 0.875, 0.25]} rotation={[Math.PI, 0, 0]} />
                </group>
                <group position={[0.187, 27.709, 6.094]} rotation={[0, -Math.PI / 2, 0]} scale={[0.503, 0.488, 0.488]}>
                  <group position={[0, 0.875, 0]} rotation={[-Math.PI, 0, Math.PI]} scale={-1}>
                    <mesh geometry={nodes.Geom3D_Piano_Hinge_Leaf_29.geometry} material={materials['[Color_000]']} />
                    <mesh geometry={nodes.Geom3D_35.geometry} material={materials['[Color_000]']} />
                  </group>
                  <mesh geometry={nodes.Geom3D__63.geometry} material={materials.Material1} />
                  <mesh geometry={nodes['Geom3D_Piano_Hinge_Leaf#2_29'].geometry} material={materials.Material1} position={[-0.999, 0.875, 0.25]} rotation={[Math.PI, 0, 0]} />
                </group>
                <group position={[0.187, 27.709, 12.124]} rotation={[0, -Math.PI / 2, 0]} scale={[0.503, 0.488, 0.488]}>
                  <group position={[0, 0.875, 0]} rotation={[-Math.PI, 0, Math.PI]} scale={-1}>
                    <mesh geometry={nodes.Geom3D_Piano_Hinge_Leaf_30.geometry} material={materials['[Color_000]']} />
                    <mesh geometry={nodes.Geom3D_36.geometry} material={materials['[Color_000]']} />
                  </group>
                  <mesh geometry={nodes.Geom3D__64.geometry} material={materials.Material1} />
                  <mesh geometry={nodes['Geom3D_Piano_Hinge_Leaf#2_30'].geometry} material={materials.Material1} position={[-0.999, 0.875, 0.25]} rotation={[Math.PI, 0, 0]} />
                </group>
                <group position={[0.187, 27.709, 18.155]} rotation={[0, -Math.PI / 2, 0]} scale={[0.503, 0.488, 0.488]}>
                  <group position={[0, 0.875, 0]} rotation={[-Math.PI, 0, Math.PI]} scale={-1}>
                    <mesh geometry={nodes.Geom3D_Piano_Hinge_Leaf_31.geometry} material={materials['[Color_000]']} />
                    <mesh geometry={nodes.Geom3D_37.geometry} material={materials['[Color_000]']} />
                  </group>
                  <mesh geometry={nodes.Geom3D__65.geometry} material={materials.Material1} />
                  <mesh geometry={nodes['Geom3D_Piano_Hinge_Leaf#2_31'].geometry} material={materials.Material1} position={[-0.999, 0.875, 0.25]} rotation={[Math.PI, 0, 0]} />
                </group>
                <mesh geometry={nodes.Geom3D__66.geometry} material={materials.Material1} position={[-0.375, 0, 0]} />
              </group>
              <mesh geometry={nodes.Geom3D_4.geometry} material={materials.Material} position={[0.25, 1.431, 15.874]} />
            </group>
            <group position={[0.569, 77.816, 1.505]}>
              <group position={[0.25, 0, 0]}>
                <group position={[0.187, 27.709, 24.186]} rotation={[0, -Math.PI / 2, 0]} scale={[0.503, 0.488, 0.488]}>
                  <group position={[0, 0.875, 0]} rotation={[-Math.PI, 0, Math.PI]} scale={-1}>
                    <mesh geometry={nodes.Geom3D_Piano_Hinge_Leaf_32.geometry} material={materials['[Color_000]']} />
                    <mesh geometry={nodes.Geom3D_38.geometry} material={materials['[Color_000]']} />
                  </group>
                  <mesh geometry={nodes.Geom3D__67.geometry} material={materials.Material1} />
                  <mesh geometry={nodes['Geom3D_Piano_Hinge_Leaf#2_32'].geometry} material={materials.Material1} position={[-0.999, 0.875, 0.25]} rotation={[Math.PI, 0, 0]} />
                </group>
                <group position={[0.187, 27.709, 30.217]} rotation={[0, -Math.PI / 2, 0]} scale={[0.503, 0.488, 0.488]}>
                  <group position={[0, 0.875, 0]} rotation={[-Math.PI, 0, Math.PI]} scale={-1}>
                    <mesh geometry={nodes.Geom3D_Piano_Hinge_Leaf_33.geometry} material={materials['[Color_000]']} />
                    <mesh geometry={nodes.Geom3D_39.geometry} material={materials['[Color_000]']} />
                  </group>
                  <mesh geometry={nodes.Geom3D__68.geometry} material={materials.Material1} />
                  <mesh geometry={nodes['Geom3D_Piano_Hinge_Leaf#2_33'].geometry} material={materials.Material1} position={[-0.999, 0.875, 0.25]} rotation={[Math.PI, 0, 0]} />
                </group>
                <group position={[0.187, 27.709, 0.062]} rotation={[0, -Math.PI / 2, 0]} scale={[0.503, 0.488, 0.488]}>
                  <group position={[0, 0.875, 0]} rotation={[-Math.PI, 0, Math.PI]} scale={-1}>
                    <mesh geometry={nodes.Geom3D_Piano_Hinge_Leaf_34.geometry} material={materials['[Color_000]']} />
                    <mesh geometry={nodes.Geom3D_40.geometry} material={materials['[Color_000]']} />
                  </group>
                  <mesh geometry={nodes.Geom3D__69.geometry} material={materials.Material1} />
                  <mesh geometry={nodes['Geom3D_Piano_Hinge_Leaf#2_34'].geometry} material={materials.Material1} position={[-0.999, 0.875, 0.25]} rotation={[Math.PI, 0, 0]} />
                </group>
                <group position={[0.187, 27.709, 6.094]} rotation={[0, -Math.PI / 2, 0]} scale={[0.503, 0.488, 0.488]}>
                  <group position={[0, 0.875, 0]} rotation={[-Math.PI, 0, Math.PI]} scale={-1}>
                    <mesh geometry={nodes.Geom3D_Piano_Hinge_Leaf_35.geometry} material={materials['[Color_000]']} />
                    <mesh geometry={nodes.Geom3D_41.geometry} material={materials['[Color_000]']} />
                  </group>
                  <mesh geometry={nodes.Geom3D__70.geometry} material={materials.Material1} />
                  <mesh geometry={nodes['Geom3D_Piano_Hinge_Leaf#2_35'].geometry} material={materials.Material1} position={[-0.999, 0.875, 0.25]} rotation={[Math.PI, 0, 0]} />
                </group>
                <group position={[0.187, 27.709, 12.124]} rotation={[0, -Math.PI / 2, 0]} scale={[0.503, 0.488, 0.488]}>
                  <group position={[0, 0.875, 0]} rotation={[-Math.PI, 0, Math.PI]} scale={-1}>
                    <mesh geometry={nodes.Geom3D_Piano_Hinge_Leaf_36.geometry} material={materials['[Color_000]']} />
                    <mesh geometry={nodes.Geom3D_42.geometry} material={materials['[Color_000]']} />
                  </group>
                  <mesh geometry={nodes.Geom3D__71.geometry} material={materials.Material1} />
                  <mesh geometry={nodes['Geom3D_Piano_Hinge_Leaf#2_36'].geometry} material={materials.Material1} position={[-0.999, 0.875, 0.25]} rotation={[Math.PI, 0, 0]} />
                </group>
                <group position={[0.187, 27.709, 18.155]} rotation={[0, -Math.PI / 2, 0]} scale={[0.503, 0.488, 0.488]}>
                  <group position={[0, 0.875, 0]} rotation={[-Math.PI, 0, Math.PI]} scale={-1}>
                    <mesh geometry={nodes.Geom3D_Piano_Hinge_Leaf_37.geometry} material={materials['[Color_000]']} />
                    <mesh geometry={nodes.Geom3D_43.geometry} material={materials['[Color_000]']} />
                  </group>
                  <mesh geometry={nodes.Geom3D__72.geometry} material={materials.Material1} />
                  <mesh geometry={nodes['Geom3D_Piano_Hinge_Leaf#2_37'].geometry} material={materials.Material1} position={[-0.999, 0.875, 0.25]} rotation={[Math.PI, 0, 0]} />
                </group>
                <mesh geometry={nodes.Geom3D__73.geometry} material={materials.Material1} position={[-0.375, 0, 0]} />
              </group>
              <mesh geometry={nodes.Geom3D_5.geometry} material={materials.Material} position={[0.25, 1.431, 15.874]} />
            </group>
            <mesh geometry={nodes.Geom3D_.geometry} material={nodes.Geom3D_.material} position={[1.006, 10.316, 0.005]} />
            <mesh geometry={nodes.Geom3D__1.geometry} material={nodes.Geom3D__1.material} position={[1.006, 27.306, 0.005]} />
            <mesh geometry={nodes.Geom3D__2.geometry} material={materials.Material1} position={[14.006, 6.557, 13.205]} />
            <mesh geometry={nodes.Geom3D__3.geometry} material={nodes.Geom3D__3.material} position={[14.131, 6.557, 13.205]} />
            <mesh geometry={nodes.Geom3D__4.geometry} material={materials.Material1} position={[14.256, 9.316, 24.505]} />
            <mesh geometry={nodes.Geom3D__5.geometry} material={materials.Material1} position={[65.756, 6.557, 13.205]} />
            <mesh geometry={nodes.Geom3D__6.geometry} material={materials.Material1} position={[65.881, 6.557, 13.205]} />
            <mesh geometry={nodes.Geom3D__7.geometry} material={materials.Material1} position={[64.506, 27.306, 0.005]} />
            <mesh geometry={nodes.Geom3D__8.geometry} material={materials.Material1} position={[79.006, 9.316, 37.755]} rotation={[-Math.PI, 0, 0]} scale={-1} />
            <mesh geometry={nodes.Geom3D__9.geometry} material={nodes.Geom3D__9.material} position={[64.506, 105.566, 0.005]} />
            <mesh geometry={nodes.Geom3D__10.geometry} material={materials.Material1} position={[64.506, 9.316, 0.005]} />
            <mesh geometry={nodes.Geom3D__11.geometry} material={materials.Material1} position={[64.506, 75.316, 0.005]} />
            <mesh geometry={nodes.Geom3D__12.geometry} material={materials.Material1} position={[79.006, 10.316, 0.005]} rotation={[-Math.PI, 0, 0]} scale={-1} />
            <mesh geometry={nodes.Geom3D__13.geometry} material={materials.Material1} position={[79.006, 78.576, 0.005]} rotation={[-Math.PI, 0, 0]} scale={-1} />
            <mesh geometry={nodes.Geom3D__15.geometry} material={materials.Material1} position={[1.006, 78.576, 0.005]} />
            <mesh geometry={nodes.Geom3D__16.geometry} material={materials.Material1} position={[1.006, 105.566, 0.005]} />
            <mesh geometry={nodes.Geom3D__17.geometry} material={nodes.Geom3D__17.material} position={[79.318, 10.066, 37.755]} rotation={[-Math.PI, 0, 0]} scale={-1} />
            <mesh geometry={nodes.Geom3D__18.geometry} material={nodes.Geom3D__18.material} position={[36.085, 7.616, 23.005]} />
            <mesh geometry={nodes.Geom3D__19.geometry} material={nodes.Geom3D__19.material} position={[1.006, 9.316, 37.755]} />
            <mesh geometry={nodes.Geom3D__20.geometry} material={nodes.Geom3D__20.material} position={[1.006, 9.316, 0.005]} />
            <mesh geometry={nodes.Geom3D__21.geometry} material={nodes.Geom3D__21.material} position={[0.693, 10.066, 37.755]} />
            <mesh geometry={nodes.Geom3D__22.geometry} material={materials.Material1} position={[15.506, 105.566, 14.864]} />
            <mesh geometry={nodes.Geom3D__23.geometry} material={materials.Metal_32_1K} position={[1.006, 53.613, 14.864]} />
            <mesh geometry={nodes.Geom3D__24.geometry} material={materials.Material1} position={[1.006, 75.316, 0.005]} />
            <mesh geometry={nodes.Geom3D__25.geometry} material={materials.Metal_32_1K} position={[1.006, 9.316, 0.005]} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/RAM-2500HD-CC-696j-Body.glb')
